version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3305:3305"

  web:
    build: .
    command: rails s -p 3002 -b '0.0.0.0'
    volumes:
      - .:/server
    ports:
      - "3002:3002"
    links:
      - db